### ISSUE TITLE
Projects to add

### ISSUE THREAD

**Issue by torch2424** [torch2424/made-with-webassembly#12]
~~https://www.eff.org/https-everywhere - Can't find like any technical blog or anything on this~~ :cry:

**Comment by torch2424** [comment]
Need to finish going through: https://twitter.com/JamesLMilner/status/1151824280914731008

And add the projects @MaxGraey mentioned to me: https://twitter.com/MaxGraey/status/1199042837402271744

**Comment by boyanio** [comment]
Hey. Here also a demo project a did some time ago https://boyan.io/wasm-wheel/

**Comment by torch2424** [comment]
@boyanio Thanks for sharing 😄 

This is super AWESOME! 🎉 Rad that you highlight so many languages here!

I'll try and add this once I have the time sometime this week, or feel free to just add a markdown file in the showcase directory in a PR 😄 . All the infor is in the README for adding projects. But no pressure! I can totally add it myself 👍 

Thanks!

**Comment by torch2424** [comment]
Livesplit by @Cryze . It's an awesome project I don't know how I forgot 😢 

https://livesplit.org/

**Comment by MaxGraey** [comment]
Also uBlock Origin extension used WebAssembly: https://www.ghacks.net/2018/12/03/ublock-origin-performance-improvements-thanks-to-wasm-firefox-only-for-now/

**Comment by torch2424** [comment]
https://twitter.com/rijubrata/status/1199057341204848642?s=19

**Comment by robertaboukhalil** [comment]
A few more :)
- sqlite (https://github.com/kripken/sql.js/)
- jq (https://github.com/robertaboukhalil/jqkungfu)
- pyiodide (https://hacks.mozilla.org/2019/04/pyodide-bringing-the-scientific-python-stack-to-the-browser/)
- 1password (https://blog.1password.com/1password-x-may-2019-update/)

I'll try to help with some of these tonight

**Comment by torch2424** [comment]
Ah, thank you @MaxGraey and @robertaboukhalil ! 😄 👏

**Comment by torch2424** [comment]
https://twitter.com/PetrBrzek/status/1199092844708945930

**Comment by MaxGraey** [comment]
Also Godot engine: https://godotengine.org/article/csharp-wasm-aot

**Comment by beriberikix** [comment]
I'm creating this list for my own tracking, but will happily create the appropriate PRs 😛 

- [ ] Envoy: https://github.com/envoyproxy/envoy-wasm, https://www.youtube.com/watch?v=OIUPf8m7CGA
- [ ] Open Policy Agent (OPA): https://blog.openpolicyagent.org/opa-v0-15-1-rego-on-webassembly-81c226c51be4
- [ ] Superpowered: https://superpowered.com/introducing-superpowered-2
- [ ] Filament: https://github.com/google/filament
- [ ] Meshoptimizer: https://github.com/zeux/meshoptimizer
- [ ] stdlib: https://github.com/stdlib-js/stdlib
- [ ] onnx.js: https://github.com/Microsoft/onnxjs
- [ ] https://webassembly.studio/
- [ ] Docker/containrd: via https://www.youtube.com/watch?v=QKTh5Xj60pI, https://github.com/dmcgowan/containerd-wasm
- [ ] Dropbox: https://blogs.dropbox.com/tech/2018/06/building-better-compression-together-with-divans/, https://github.com/dropbox/divans
- [ ] ogv.js: https://github.com/brion/ogv.js
- [ ] https://picovoice.ai/
- [ ] https://floooh.github.io/tiny8bit/
- [ ] https://chirp.io/
- [ ] godot: https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_web.html

I'll keep adding as I dig up old links :)

**Comment by torch2424** [comment]
@beriberikix WOOOAAAHHH! Thank you so much! This is rad! 😀

**Comment by torch2424** [comment]
@robertaboukhalil 's new project! 😄 https://twitter.com/RobAboukhalil/status/1201919419489800192

**Comment by torch2424** [comment]
TensorFlow: https://twitter.com/yashints/status/1207088217838800898

**Comment by torch2424** [comment]
https://twitter.com/JimmyKane9/status/1210936386561413121?s=19

**Comment by torch2424** [comment]
https://blog.scottlogic.com/2020/01/03/webassembly-sudoku-solver.html

**Comment by torch2424** [comment]
I'm going through and ~~crossing out~~ all projects I have on my current branch, until we can close this issue once all projects have been added :smile: :+1:

**Comment by beriberikix** [comment]
🤚 I'd like to help! Should I just start submitting PRs for the ones I listed? Or how best to not make *more* work for you?

**Comment by torch2424** [comment]
@beriberikix Oh yes! Please I was just thinking I really need some help with this haha! :joy: 

Yep, just start submitting PRs and that would be great! Especially from your list: https://github.com/torch2424/made-with-webassembly/issues/12#issuecomment-558426525

I just finished up everything up to: https://github.com/torch2424/made-with-webassembly/issues/12#issuecomment-558383337

Meaning, I'll go ahead and merge my branch, and then start on the last few things I found: https://github.com/torch2424/made-with-webassembly/issues/12#issuecomment-561308238

Does that work for you? And again, thank you soooo much! :smile: :+1:

**Comment by vshymanskyy** [comment]
@torch2424 would [`Wasm3`](https://github.com/wasm3/wasm3) qualify? :smiley:

**Comment by beriberikix** [comment]
@vshymanskyy yes! PR welcome 😄

**Comment by MaxGraey** [comment]
(chess)[https://github.com/mhonert/chess] - A free and open source chess game using AssemblyScript and React

**Comment by vshymanskyy** [comment]
@torch2424 @beriberikix @MaxGraey hope this renders fine: https://github.com/torch2424/made-with-webassembly/pull/42

**Comment by torch2424** [comment]
Awesome, I moved your comment to #43 @MaxGraey :smile: 

And Merged both @vshymanskyy and @beriberikix PR. Meaning this mega list is now complete! :smile: :+1: 

Closing this issue...
