### ISSUE TITLE
Fix fastq description - Talks about Figma

### ISSUE THREAD

**Issue by torch2424** [torch2424/made-with-webassembly#14]
https://twitter.com/siuyee/status/1199048877187436544

**Comment by robertaboukhalil** [comment]
You can assign this one to me :)

**Comment by torch2424** [comment]
@robertaboukhalil Thanks! 😄 Yeah it was just a product of me copying files to make the next one 😂

**Comment by torch2424** [comment]
Fixed by #17 😄
