### ISSUE TITLE
Website link for Pajama Sam 3 is dead

### ISSUE THREAD

**Issue by XRFXLP** [torch2424/made-with-webassembly#97]
The site which is directed by "website" [here](https://madewithwebassembly.com/showcase/pajamasam3/) is [dead](https://classic-arcade.itch.io/pajama-sam-3)
![image](https://user-images.githubusercontent.com/23459568/164891933-6ecb8694-4cb3-405a-b6ab-ced9be81c94f.png)

**Comment by torch2424** [comment]
Oh no! That's a bummer. Well I'll go ahead and remove it than. Thanks for the heads up! 😄 🙏🏾
